[GENERAL]
SIMILARITY_MEASURE = "cosine" # "cosine" or "dot"
KEEP_ALIVE = "5m" # How long to keep Ollama models loaded into memory. (Instead of using -1 use "-1m")

[MODELS.GROQ]
API_KEY = "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"

[MODELS.GEMINI]
API_KEY = "AIzaSyCsfF7UAxLpd8N4jjQdsk4o1HABSLwFzBw"

[API_ENDPOINTS]
SEARXNG = "https://koss8o84oc8owkocw8okw800.coolify.infoboi.site" # SearxNG API URL - http://localhost:32768
